name: Update Godot SDK on Godot Asset Library

on: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create archive
        run: |
          cd Godot
          zip -r NeuroSdk.zip addons neuro_sdk_config.gd
      
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: Godot/NeuroSdk.zip
          tag: godot
          overwrite: true
          make_latest: false
      
      #- name: Update Godot Asset Library metadata
      #  uses: deep-entertainment/godot-asset-lib-action@v0.4.0
      #  with:
      #    assetId: ${{ vars.GODOT_ASSET_LIBRARY_ASSET_ID }}
      #    username: ${{ secrets.GODOT_ASSET_LIBRARY_USERNAME }}
      #    password: ${{ secrets.GODOT_ASSET_LIBRARY_PASSWORD }}
      #    assetTemplate: Godot/.asset-metadata.json